"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { apiUrl } from "@/lib/api";

type DraftStatus = "PENDING" | "APPROVED" | "REJECTED";

type AIDraftModule = {
  id: string;
  name: string;
  description?: string | null;
  minPlan: "FREE" | "PRO" | "ENTERPRISE";
  status: DraftStatus;
  createdAt: string;

  // These are text previews generated by AI (safe to render as code blocks)
  schemaDiff?: string | null;
  routesPreview?: string | null;
  permissions?: string[] | null;
};

export default function AIDraftReviewPage() {
  const params = useParams();
  const router = useRouter();
  const id = params.id as string;

  const [draft, setDraft] = useState<AIDraftModule | null>(null);
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState<"approve" | "reject" | null>(null);

  useEffect(() => {
    const fetchDraft = async () => {
      try {
        const res = await fetch(apiUrl(`/api/admin/ai-modules/${id}`), {
          credentials: "include",
        });
        if (!res.ok) throw new Error("Failed to load draft");
        const data = await res.json();
        setDraft(data.draft);
      } catch {
        setDraft(null);
      } finally {
        setLoading(false);
      }
    };

    fetchDraft();
  }, [id]);

  const handleApprove = async () => {
    setActionLoading("approve");
    await fetch(apiUrl(`/api/admin/ai-modules/${id}/approve`), {
      method: "POST",
      credentials: "include",
    });
    router.push("/admin/ai-modules");
  };

  const handleReject = async () => {
    setActionLoading("reject");
    await fetch(apiUrl(`/api/admin/ai-modules/${id}/reject`), {
      method: "POST",
      credentials: "include",
    });
    router.push("/admin/ai-modules");
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-950 p-8 text-slate-400">
        Loading AI draft…
      </div>
    );
  }

  if (!draft) {
    return (
      <div className="min-h-screen bg-slate-950 p-8 text-slate-400">
        Draft not found.
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-950 p-6 md:p-8 space-y-8">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-white tracking-tight">
            {draft.name}
          </h1>
          <p className="text-sm text-slate-400 mt-1">
            AI-generated module draft review
          </p>
        </div>

        <Link
          href="/admin/ai-modules"
          className="text-sm text-cyan-400 hover:text-cyan-300"
        >
          ← Back to drafts
        </Link>
      </div>

      {/* Metadata */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="rounded-xl border border-slate-800 bg-slate-900 p-4">
          <p className="text-xs text-slate-400">Minimum Plan</p>
          <p className="text-sm font-medium text-white mt-1">
            {draft.minPlan}
          </p>
        </div>

        <div className="rounded-xl border border-slate-800 bg-slate-900 p-4">
          <p className="text-xs text-slate-400">Status</p>
          <p className="text-sm font-medium text-white mt-1">
            {draft.status}
          </p>
        </div>

        <div className="rounded-xl border border-slate-800 bg-slate-900 p-4">
          <p className="text-xs text-slate-400">Created</p>
          <p className="text-sm font-medium text-white mt-1">
            {new Date(draft.createdAt).toLocaleString()}
          </p>
        </div>
      </div>

      {/* Description */}
      {draft.description && (
        <div className="rounded-xl border border-slate-800 bg-slate-900 p-6">
          <h2 className="text-sm font-semibold text-white mb-2">Description</h2>
          <p className="text-sm text-slate-300 leading-relaxed">
            {draft.description}
          </p>
        </div>
      )}

      {/* Permissions */}
      {draft.permissions && draft.permissions.length > 0 && (
        <div className="rounded-xl border border-slate-800 bg-slate-900 p-6">
          <h2 className="text-sm font-semibold text-white mb-3">
            Required Permissions
          </h2>
          <div className="flex flex-wrap gap-2">
            {draft.permissions.map((perm) => (
              <span
                key={perm}
                className="rounded-full border border-slate-700 bg-slate-800 px-3 py-1 text-xs text-slate-300"
              >
                {perm}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Prisma Diff */}
      {draft.schemaDiff && (
        <div className="rounded-xl border border-slate-800 bg-slate-900 p-6">
          <h2 className="text-sm font-semibold text-white mb-3">
            Prisma Schema Diff
          </h2>
          <pre className="max-h-96 overflow-auto rounded-lg bg-black p-4 text-xs text-cyan-300">
            {draft.schemaDiff}
          </pre>
        </div>
      )}

      {/* Routes Preview */}
      {draft.routesPreview && (
        <div className="rounded-xl border border-slate-800 bg-slate-900 p-6">
          <h2 className="text-sm font-semibold text-white mb-3">
            Backend Routes Preview
          </h2>
          <pre className="max-h-96 overflow-auto rounded-lg bg-black p-4 text-xs text-cyan-300">
            {draft.routesPreview}
          </pre>
        </div>
      )}

      {/* Actions */}
      {draft.status === "PENDING" && (
        <div className="flex gap-4 pt-4">
          <button
            onClick={handleApprove}
            disabled={actionLoading !== null}
            className="rounded-lg bg-cyan-600 px-6 py-2.5 text-sm font-semibold text-white shadow-lg shadow-cyan-500/25 hover:bg-cyan-500 disabled:opacity-50"
          >
            {actionLoading === "approve" ? "Approving…" : "Approve Module"}
          </button>

          <button
            onClick={handleReject}
            disabled={actionLoading !== null}
            className="rounded-lg bg-red-600 px-6 py-2.5 text-sm font-semibold text-white shadow-lg shadow-red-500/25 hover:bg-red-500 disabled:opacity-50"
          >
            {actionLoading === "reject" ? "Rejecting…" : "Reject Draft"}
          </button>
        </div>
      )}
    </div>
  );
}
