// src/utils/errorCodes.ts

// Central error code registry for the API
export const ErrorCode = {
  // 400-level
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_FIELD: 'MISSING_FIELD',

  // 401-level
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  UNAUTHORIZED: 'UNAUTHORIZED',

  // 403-level
  FORBIDDEN: 'FORBIDDEN',

  // 404-level
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  MODULE_NOT_FOUND: 'MODULE_NOT_FOUND',
  DRAFT_NOT_FOUND: 'DRAFT_NOT_FOUND',

  // 409-level
  CONFLICT: 'CONFLICT',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  MODULE_EXISTS: 'MODULE_EXISTS',
  VERSION_EXISTS: 'VERSION_EXISTS',

  // 422-level
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',
  INSUFFICIENT_PLAN: 'INSUFFICIENT_PLAN',

  // 500-level
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',

  // Stripe
  STRIPE_ERROR: 'STRIPE_ERROR',
  STRIPE_NOT_CONFIGURED: 'STRIPE_NOT_CONFIGURED',
  STRIPE_WEBHOOK_ERROR: 'STRIPE_WEBHOOK_ERROR',
  STRIPE_CUSTOMER_ERROR: 'STRIPE_CUSTOMER_ERROR',

  // Session / service
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

// Fully explicit map from error code → HTTP status
export const ErrorStatusMap: Record<ErrorCodeType, number> = {
  // 400
  VALIDATION_ERROR: 400,
  INVALID_INPUT: 400,
  MISSING_FIELD: 400,

  // 401
  AUTHENTICATION_ERROR: 401,
  INVALID_CREDENTIALS: 401,
  TOKEN_EXPIRED: 401,
  TOKEN_INVALID: 401,
  UNAUTHORIZED: 401,

  // 403
  FORBIDDEN: 403,

  // 404
  NOT_FOUND: 404,
  USER_NOT_FOUND: 404,
  MODULE_NOT_FOUND: 404,
  DRAFT_NOT_FOUND: 404,

  // 409
  CONFLICT: 409,
  EMAIL_EXISTS: 409,
  MODULE_EXISTS: 409,
  VERSION_EXISTS: 409,

  // 422
  INSUFFICIENT_ROLE: 422,
  INSUFFICIENT_PLAN: 422,

  // 500
  INTERNAL_ERROR: 500,
  DATABASE_ERROR: 500,
  STRIPE_ERROR: 500,
  STRIPE_NOT_CONFIGURED: 500,
  STRIPE_WEBHOOK_ERROR: 500,
  STRIPE_CUSTOMER_ERROR: 500,
  SESSION_EXPIRED: 500,
  SERVICE_UNAVAILABLE: 503,
};



